-- Made by tests/tools/make_real_lines.lua: Combat Log lines exactly as the game's own code
-- writes them, and what BattleText should read from each. Don't edit by hand.
return {
    { id = "swing",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_DAMAGE|h|cffffffffMelee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff27|r |cffffffffPhysical|r. ",
      expect = { amount = 27, fromMe = true, kind = "damage", melee = true, unit = "Physical" } },
    { id = "swing, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_DAMAGE|h|cffffffffMelee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff56|r |cffffffffPhysical|r. (Critical) ",
      expect = { amount = 56, crit = true, fromMe = true, kind = "damage", melee = true, unit = "Physical" } },
    { id = "swing, glancing",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_DAMAGE|h|cffffffffMelee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff20|r |cffffffffPhysical|r. (Glancing) ",
      expect = { amount = 20, fromMe = true, glancing = true, kind = "damage", melee = true, unit = "Physical" } },
    { id = "swing, partly blocked",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_DAMAGE|h|cffffffffMelee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff26|r |cffffffffPhysical|r. (3 Blocked) ",
      expect = { amount = 26, blocked = 3, fromMe = true, kind = "damage", melee = true, unit = "Physical" } },
    { id = "swing, overkill",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_DAMAGE|h|cffffffffMelee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff17|r |cffffffffPhysical|r. (35 Overkill) ",
      expect = { amount = 17, fromMe = true, kind = "damage", melee = true, overkill = 35, unit = "Physical" } },
    { id = "swing, thousands, absorbed, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_DAMAGE|h|cffffffffMelee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff1,234|r |cffffffffPhysical|r. (1,200 Absorbed) (Critical) ",
      expect = { absorbed = 1200, amount = 1234, crit = true, fromMe = true, kind = "damage", melee = true, unit = "Physical" } },
    { id = "swing, millions",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_DAMAGE|h|cffffffffMelee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff1,234,567|r |cffffffffPhysical|r. ",
      expect = { amount = 1234567, fromMe = true, kind = "damage", melee = true, unit = "Physical" } },
    { id = "swing at me",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_DAMAGE|h|cffff1313Melee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff131312|r |cffff1313Physical|r. (3 Blocked) ",
      expect = { amount = 12, blocked = 3, kind = "damage", melee = true, toMe = true, unit = "Physical" } },
    { id = "swing at me, crushing",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_DAMAGE|h|cffff1313Melee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff131380|r |cffff1313Physical|r. (Crushing) ",
      expect = { amount = 80, crushing = true, kind = "damage", melee = true, toMe = true, unit = "Physical" } },
    { id = "swing at me, crit",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_DAMAGE|h|cffff1313Melee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff131380|r |cffff1313Physical|r. (Critical) ",
      expect = { amount = 80, crit = true, kind = "damage", melee = true, toMe = true, unit = "Physical" } },
    { id = "pet's swing",
      raw = "|Hunit:Pet-0-1-2-3-4-000002:Fluffy Zapsu|hFluffy Zapsu|h |Haction:SWING_DAMAGE|h|cffffffffMelee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff20|r |cffffffffPhysical|r. ",
      expect = { amount = 20, kind = "damage", melee = true, srcGUID = "Pet-0-1-2-3-4-000002", unit = "Physical" } },
    { id = "swing at the pet",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_DAMAGE|h|cffff1313Melee|r|h |Haction:SWING_DAMAGE|hhit|h |Hunit:Pet-0-1-2-3-4-000002:Fluffy Zapsu|hFluffy Zapsu|h |cffff13139|r |cffff1313Physical|r. ",
      expect = { amount = 9, kind = "damage", melee = true, srcGUID = "Creature-0-1-2-3-4-000001", unit = "Physical" } },
    { id = "spell",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffffffClaw|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff50|r |cffffffffPhysical|r. (1 Blocked) ",
      expect = { amount = 50, blocked = 1, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "spell, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_DAMAGE|h|cffffffffMoonfire|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff112|r |cffffffffArcane|r. (Critical) ",
      expect = { amount = 112, crit = true, fromMe = true, kind = "damage", spell = "Moonfire", spellId = 8921, unit = "Arcane" } },
    { id = "spell, partly resisted",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:133:0:SPELL_DAMAGE|h|cffffffffFireball|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff75|r |cffffffffFire|r. (25 Resisted) ",
      expect = { amount = 75, fromMe = true, kind = "damage", resisted = 25, spell = "Fireball", spellId = 133, unit = "Fire" } },
    { id = "spell, resisted, absorbed, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:133:0:SPELL_DAMAGE|h|cffffffffFireball|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff2,500|r |cffffffffFire|r. (1,250 Resisted) (300 Absorbed) (Critical) ",
      expect = { absorbed = 300, amount = 2500, crit = true, fromMe = true, kind = "damage", resisted = 1250, spell = "Fireball", spellId = 133, unit = "Fire" } },
    { id = "spell of two schools",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:44614:0:SPELL_DAMAGE|h|cffffffffFrostfire Bolt|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff90|r |cffffffffFrostfire|r. ",
      expect = { amount = 90, fromMe = true, kind = "damage", spell = "Frostfire Bolt", spellId = 44614, unit = "Frostfire" } },
    { id = "spell name with brackets",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16857:0:SPELL_DAMAGE|h|cffffffffFaerie Fire (Feral)|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff5|r |cffffffffNature|r. ",
      expect = { amount = 5, fromMe = true, kind = "damage", spell = "Faerie Fire (Feral)", spellId = 16857, unit = "Nature" } },
    { id = "spell name with a period",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:1:0:SPELL_DAMAGE|h|cffffffffMr. Pinchy's Gift|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff5|r |cffffffffNature|r. ",
      expect = { amount = 5, fromMe = true, kind = "damage", spell = "Mr. Pinchy's Gift", spellId = 1, unit = "Nature" } },
    { id = "spell name with a number",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:1:0:SPELL_DAMAGE|h|cffffffffGoblin Bomb 9000|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff300|r |cffffffffFire|r. ",
      expect = { amount = 300, fromMe = true, kind = "damage", spell = "Goblin Bomb 9000", spellId = 1, unit = "Fire" } },
    { id = "spell name ending in a number",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:1:0:SPELL_DAMAGE|h|cffffffffRocket 2|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff7|r |cffffffffFire|r. ",
      expect = { amount = 7, fromMe = true, kind = "damage", spell = "Rocket 2", spellId = 1, unit = "Fire" } },
    { id = "spell name with an action word",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:1:0:SPELL_DAMAGE|h|cffffffffCritical hit Proc|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff7|r |cffffffffFire|r. ",
      expect = { amount = 7, fromMe = true, kind = "damage", spell = "Critical hit Proc", spellId = 1, unit = "Fire" } },
    { id = "target name with a number",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffffffClaw|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-1:Training Dummy 2|hTraining Dummy 2|h |cffffffff50|r |cffffffffPhysical|r. ",
      expect = { amount = 50, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "target name with an action word",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffffffClaw|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-1:Big hit Bob|hBig hit Bob|h |cffffffff50|r |cffffffffPhysical|r. ",
      expect = { amount = 50, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "target name with a period",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffffffClaw|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-1:Mr. Smite|hMr. Smite|h |cffffffff50|r |cffffffffPhysical|r. ",
      expect = { amount = 50, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "target with a raid mark",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffffffClaw|r|h |Haction:SPELL_DAMAGE|hhit|h |Hicon:128:dest|h|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8.blp:0|t|h|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff50|r |cffffffffPhysical|r. ",
      expect = { amount = 50, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "spell at me",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_DAMAGE|h|cffff1313Fireball|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff131384|r |cffff1313Fire|r. ",
      expect = { amount = 84, kind = "damage", spell = "Fireball", spellId = 133, toMe = true, unit = "Fire" } },
    { id = "spell at me, apostrophe in its name",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:1130:0:SPELL_DAMAGE|h|cffff1313Hunter's Mark|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff13135|r |cffff1313Arcane|r. ",
      expect = { amount = 5, kind = "damage", spell = "Hunter's Mark", spellId = 1130, toMe = true, unit = "Arcane" } },
    { id = "spell at me, caster's name has an action word",
      raw = "|Hunit:Creature-1:Defias hit Squad|hDefias hit Squad|h |Hspell:133:0:SPELL_DAMAGE|h|cffff1313Fireball|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff131384|r |cffff1313Fire|r. ",
      expect = { amount = 84, kind = "damage", spell = "Fireball", spellId = 133, toMe = true, unit = "Fire" } },
    { id = "spell at me, caster's name has another action word",
      raw = "|Hunit:Creature-1:The healed One|hThe healed One|h |Hspell:133:0:SPELL_DAMAGE|h|cffff1313Fireball|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff131384|r |cffff1313Fire|r. ",
      expect = { amount = 84, kind = "damage", spell = "Fireball", spellId = 133, toMe = true, unit = "Fire" } },
    { id = "spell at myself",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:1949:0:SPELL_DAMAGE|h|cffffffffHellfire|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff30|r |cffffffffFire|r. ",
      expect = { amount = 30, fromMe = true, kind = "damage", spell = "Hellfire", spellId = 1949, toMe = true, unit = "Fire" } },
    { id = "pet's spell",
      raw = "|Hunit:Pet-0-1-2-3-4-000002:Fluffy Zapsu|hFluffy Zapsu|h |Hspell:17253:0:SPELL_DAMAGE|h|cffffffffBite|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff20|r |cffffffffPhysical|r. ",
      expect = { amount = 20, kind = "damage", spell = "Bite", spellId = 17253, srcGUID = "Pet-0-1-2-3-4-000002", unit = "Physical" } },
    { id = "shot",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_DAMAGE|h|cffffffffAuto Shot|r|h |Haction:RANGE_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff44|r |cffffffffPhysical|r. ",
      expect = { amount = 44, fromMe = true, kind = "damage", spell = "Auto Shot", unit = "Physical" } },
    { id = "shot, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_DAMAGE|h|cffffffffAuto Shot|r|h |Haction:RANGE_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff88|r |cffffffffPhysical|r. (Critical) ",
      expect = { amount = 88, crit = true, fromMe = true, kind = "damage", spell = "Auto Shot", unit = "Physical" } },
    { id = "shot at me",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:RANGE_DAMAGE|h|cffff1313Shoot|r|h |Haction:RANGE_DAMAGE|hhit|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff131314|r |cffff1313Physical|r. ",
      expect = { amount = 14, kind = "damage", spell = "Shoot", toMe = true, unit = "Physical" } },
    { id = "shot fails: MISS",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Missed) ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", spell = "Shot" } },
    { id = "shot fails: DODGE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", missType = "DODGE", spell = "Shot" } },
    { id = "shot fails: PARRY",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Parried) ",
      expect = { fromMe = true, kind = "miss", missType = "PARRY", spell = "Shot" } },
    { id = "shot fails: BLOCK",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Blocked) ",
      expect = { blocked = 15, fromMe = true, kind = "miss", missType = "BLOCK", spell = "Shot" } },
    { id = "shot fails: RESIST",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Resisted) ",
      expect = { fromMe = true, kind = "miss", missType = "RESIST", resisted = 15, spell = "Shot" } },
    { id = "shot fails: ABSORB",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Absorbed) ",
      expect = { absorbed = 15, fromMe = true, kind = "miss", missType = "ABSORB", spell = "Shot" } },
    { id = "shot fails: IMMUNE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Immune) ",
      expect = { fromMe = true, kind = "miss", missType = "IMMUNE", spell = "Shot" } },
    { id = "shot fails: EVADE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Evaded) ",
      expect = { fromMe = true, kind = "miss", missType = "EVADE", spell = "Shot" } },
    { id = "shot fails: DEFLECT",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:RANGE_MISSED|h|cffffffffShot|r|h |Haction:RANGE_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Deflected) ",
      expect = { fromMe = true, kind = "miss", missType = "DEFLECT", spell = "Shot" } },
    { id = "tick",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_DAMAGE|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_DAMAGE|hdamaged|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff9|r |cffffffffPhysical|r. ",
      expect = { amount = 9, fromMe = true, kind = "damage", periodic = true, spell = "Rend", spellId = 772, unit = "Physical" } },
    { id = "tick, absorbed, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:172:0:SPELL_PERIODIC_DAMAGE|h|cffffffffCorruption|r|h |Haction:SPELL_PERIODIC_DAMAGE|hdamaged|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff90|r |cffffffffShadow|r. (10 Absorbed) (Critical) ",
      expect = { absorbed = 10, amount = 90, crit = true, fromMe = true, kind = "damage", periodic = true, spell = "Corruption", spellId = 172, unit = "Shadow" } },
    { id = "tick on me",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:744:0:SPELL_PERIODIC_DAMAGE|h|cffff1313Poison|r|h |Haction:SPELL_PERIODIC_DAMAGE|hdamaged|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff13136|r |cffff1313Nature|r. ",
      expect = { amount = 6, kind = "damage", periodic = true, spell = "Poison", spellId = 744, toMe = true, unit = "Nature" } },
    { id = "tick fails: MISS",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Tick Missed) ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "tick fails: DODGE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Tick Dodged) ",
      expect = { fromMe = true, kind = "miss", missType = "DODGE", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "tick fails: PARRY",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Tick Parried) ",
      expect = { fromMe = true, kind = "miss", missType = "PARRY", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "tick fails: BLOCK",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Tick Blocked) ",
      expect = { fromMe = true, kind = "miss", missType = "BLOCK", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "tick fails: RESIST",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Tick Resisted) ",
      expect = { fromMe = true, kind = "miss", missType = "RESIST", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "tick fails: ABSORB",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Absorbed) ",
      expect = { absorbed = 15, fromMe = true, kind = "miss", missType = "ABSORB", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "tick fails: IMMUNE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Immune) ",
      expect = { fromMe = true, kind = "miss", missType = "IMMUNE", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "tick fails: EVADE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "tick fails: DEFLECT",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:772:0:SPELL_PERIODIC_MISSED|h|cffffffffRend|r|h |Haction:SPELL_PERIODIC_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", periodic = true, spell = "Rend", spellId = 772 } },
    { id = "damage shield",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD|h|cff7f7f7fdamages|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff3|r |cffffffffNature|r. ",
      expect = { amount = 3, fromMe = true, kind = "damage", spell = "Thorns", spellId = 467, unit = "Nature" } },
    { id = "damage shield on me",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:467:0:DAMAGE_SHIELD|h|cffff1313Thorns|r|h |Haction:DAMAGE_SHIELD|h|cff7f7f7fdamages|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffff13133|r |cffff1313Nature|r. ",
      expect = { amount = 3, kind = "damage", spell = "Thorns", spellId = 467, toMe = true, unit = "Nature" } },
    { id = "damage shield fails: MISS",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Missed) ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", spell = "Thorns", spellId = 467 } },
    { id = "damage shield fails: DODGE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", missType = "DODGE", spell = "Thorns", spellId = 467 } },
    { id = "damage shield fails: PARRY",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Parried) ",
      expect = { fromMe = true, kind = "miss", missType = "PARRY", spell = "Thorns", spellId = 467 } },
    { id = "damage shield fails: BLOCK",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Blocked) ",
      expect = { fromMe = true, kind = "miss", missType = "BLOCK", spell = "Thorns", spellId = 467 } },
    { id = "damage shield fails: RESIST",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Resisted) ",
      expect = { fromMe = true, kind = "miss", missType = "RESIST", spell = "Thorns", spellId = 467 } },
    { id = "damage shield fails: ABSORB",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", spell = "Thorns", spellId = 467 } },
    { id = "damage shield fails: IMMUNE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Immune) ",
      expect = { fromMe = true, kind = "miss", missType = "IMMUNE", spell = "Thorns", spellId = 467 } },
    { id = "damage shield fails: EVADE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", spell = "Thorns", spellId = 467 } },
    { id = "damage shield fails: DEFLECT",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:467:0:DAMAGE_SHIELD_MISSED|h|cffffffffThorns|r|h |Haction:DAMAGE_SHIELD_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Deflected) ",
      expect = { fromMe = true, kind = "miss", missType = "DEFLECT", spell = "Thorns", spellId = 467 } },
    { id = "damage shared out",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |Hspell:25228:0:DAMAGE_SPLIT|h|cffffffffSoul Link|r|h |Haction:DAMAGE_SPLIT|h|cff7f7f7fshared damage|r|h |Hunit:Pet-0-1-2-3-4-000002:Fluffy Zapsu|hFluffy Zapsu|h |cffffffff12|r |cffffffffShadow|r. ",
      expect = { amount = 12, fromMe = true, kind = "damage", spell = "Soul Link", spellId = 25228, split = true, unit = "Shadow" } },
    { id = "damage shared to me",
      raw = "|Hunit:Pet-0-1-2-3-4-000002:Fluffy Zapsu|hFluffy Zapsu|h |Hspell:25228:0:DAMAGE_SPLIT|h|cffffffffSoul Link|r|h |Haction:DAMAGE_SPLIT|h|cff7f7f7fshared damage|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff12|r |cffffffffShadow|r. ",
      expect = { amount = 12, kind = "damage", spell = "Soul Link", spellId = 25228, split = true, srcGUID = "Pet-0-1-2-3-4-000002", toMe = true, unit = "Shadow" } },
    { id = "the world: Falling",
      raw = "Unknown |Haction:ENVIRONMENTAL_DAMAGE|h|cffffffffFalling|r|h |Haction:ENVIRONMENTAL_DAMAGE|h|cff7f7f7fdamaged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff123|r |cffffffffPhysical|r. ",
      expect = { amount = 123, kind = "damage", spell = "Falling", toMe = true, unit = "Physical" } },
    { id = "the world: Drowning",
      raw = "Unknown |Haction:ENVIRONMENTAL_DAMAGE|h|cffffffffDrowning|r|h |Haction:ENVIRONMENTAL_DAMAGE|h|cff7f7f7fdamaged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff123|r |cffffffffFire|r. ",
      expect = { amount = 123, kind = "damage", spell = "Drowning", toMe = true, unit = "Fire" } },
    { id = "the world: Fire",
      raw = "Unknown |Haction:ENVIRONMENTAL_DAMAGE|h|cffffffffFire|r|h |Haction:ENVIRONMENTAL_DAMAGE|h|cff7f7f7fdamaged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff123|r |cffffffffFire|r. ",
      expect = { amount = 123, kind = "damage", spell = "Fire", toMe = true, unit = "Fire" } },
    { id = "the world: Lava",
      raw = "Unknown |Haction:ENVIRONMENTAL_DAMAGE|h|cffffffffLava|r|h |Haction:ENVIRONMENTAL_DAMAGE|h|cff7f7f7fdamaged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff123|r |cffffffffFire|r. ",
      expect = { amount = 123, kind = "damage", spell = "Lava", toMe = true, unit = "Fire" } },
    { id = "the world: Fatigue",
      raw = "Unknown |Haction:ENVIRONMENTAL_DAMAGE|h|cffffffffFatigue|r|h |Haction:ENVIRONMENTAL_DAMAGE|h|cff7f7f7fdamaged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff123|r |cffffffffFire|r. ",
      expect = { amount = 123, kind = "damage", spell = "Fatigue", toMe = true, unit = "Fire" } },
    { id = "the world: Slime",
      raw = "Unknown |Haction:ENVIRONMENTAL_DAMAGE|h|cffffffffSlime|r|h |Haction:ENVIRONMENTAL_DAMAGE|h|cff7f7f7fdamaged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff123|r |cffffffffFire|r. ",
      expect = { amount = 123, kind = "damage", spell = "Slime", toMe = true, unit = "Fire" } },
    { id = "the world, nobody named",
      raw = "|Haction:ENVIRONMENTAL_DAMAGE|h|cffffffffFalling|r|h |Haction:ENVIRONMENTAL_DAMAGE|h|cff7f7f7fdamaged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff123|r |cffffffffPhysical|r. ",
      expect = { amount = 123, kind = "damage", spell = "Falling", toMe = true, unit = "Physical" } },
    { id = "the world, thousands, absorbed",
      raw = "Unknown |Haction:ENVIRONMENTAL_DAMAGE|h|cffffffffFalling|r|h |Haction:ENVIRONMENTAL_DAMAGE|h|cff7f7f7fdamaged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff1,234|r |cffffffffPhysical|r. (20 Absorbed) ",
      expect = { absorbed = 20, amount = 1234, kind = "damage", spell = "Falling", toMe = true, unit = "Physical" } },
    { id = "swing fails: MISS",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Missed) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "MISS" } },
    { id = "swing at me fails: MISS",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Missed) ",
      expect = { kind = "miss", melee = true, missType = "MISS", toMe = true } },
    { id = "swing fails: DODGE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "DODGE" } },
    { id = "swing at me fails: DODGE",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Dodged) ",
      expect = { kind = "miss", melee = true, missType = "DODGE", toMe = true } },
    { id = "swing fails: PARRY",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Parried) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "PARRY" } },
    { id = "swing at me fails: PARRY",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Parried) ",
      expect = { kind = "miss", melee = true, missType = "PARRY", toMe = true } },
    { id = "swing fails: BLOCK",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Blocked) ",
      expect = { blocked = 15, fromMe = true, kind = "miss", melee = true, missType = "BLOCK" } },
    { id = "swing at me fails: BLOCK",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (15 Blocked) ",
      expect = { blocked = 15, kind = "miss", melee = true, missType = "BLOCK", toMe = true } },
    { id = "swing fails: RESIST",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Resisted) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "RESIST", resisted = 15 } },
    { id = "swing at me fails: RESIST",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (15 Resisted) ",
      expect = { kind = "miss", melee = true, missType = "RESIST", resisted = 15, toMe = true } },
    { id = "swing fails: ABSORB",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Absorbed) ",
      expect = { absorbed = 15, fromMe = true, kind = "miss", melee = true, missType = "ABSORB" } },
    { id = "swing at me fails: ABSORB",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (15 Absorbed) ",
      expect = { absorbed = 15, kind = "miss", melee = true, missType = "ABSORB", toMe = true } },
    { id = "swing fails: IMMUNE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Immune) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "IMMUNE" } },
    { id = "swing at me fails: IMMUNE",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Immune) ",
      expect = { kind = "miss", melee = true, missType = "IMMUNE", toMe = true } },
    { id = "swing fails: EVADE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Evaded) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "EVADE" } },
    { id = "swing at me fails: EVADE",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Evaded) ",
      expect = { kind = "miss", melee = true, missType = "EVADE", toMe = true } },
    { id = "swing fails: DEFLECT",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Deflected) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "DEFLECT" } },
    { id = "swing at me fails: DEFLECT",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:SWING_MISSED|h|cffff1313Melee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Deflected) ",
      expect = { kind = "miss", melee = true, missType = "DEFLECT", toMe = true } },
    { id = "swing blocked for nothing",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (0 Blocked) ",
      expect = { blocked = 0, fromMe = true, kind = "miss", melee = true, missType = "BLOCK" } },
    { id = "spell fails: MISS",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fMissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Missed) ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: MISS",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fMissed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Missed) ",
      expect = { kind = "miss", missType = "MISS", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: DODGE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fDodged|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", missType = "DODGE", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: DODGE",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fDodged|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Dodged) ",
      expect = { kind = "miss", missType = "DODGE", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: PARRY",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fParried|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Parried) ",
      expect = { fromMe = true, kind = "miss", missType = "PARRY", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: PARRY",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fParried|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Parried) ",
      expect = { kind = "miss", missType = "PARRY", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: BLOCK",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fBlocked|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Blocked) ",
      expect = { blocked = 15, fromMe = true, kind = "miss", missType = "BLOCK", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: BLOCK",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fBlocked|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (15 Blocked) ",
      expect = { blocked = 15, kind = "miss", missType = "BLOCK", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: RESIST",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fresisted|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "miss", missType = "RESIST", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: RESIST",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fresisted|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. ",
      expect = { kind = "miss", missType = "RESIST", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: ABSORB",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fAbsorbed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (15 Absorbed) ",
      expect = { absorbed = 15, fromMe = true, kind = "miss", missType = "ABSORB", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: ABSORB",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fAbsorbed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (15 Absorbed) ",
      expect = { absorbed = 15, kind = "miss", missType = "ABSORB", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: IMMUNE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fImmune|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Immune) ",
      expect = { fromMe = true, kind = "miss", missType = "IMMUNE", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: IMMUNE",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fImmune|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Immune) ",
      expect = { kind = "miss", missType = "IMMUNE", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: EVADE",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fEvaded|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Evaded) ",
      expect = { fromMe = true, kind = "miss", missType = "EVADE", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: EVADE",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fEvaded|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Evaded) ",
      expect = { kind = "miss", missType = "EVADE", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: DEFLECT",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fDeflected|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Deflected) ",
      expect = { fromMe = true, kind = "miss", missType = "DEFLECT", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: DEFLECT",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7fDeflected|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. (Deflected) ",
      expect = { kind = "miss", missType = "DEFLECT", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell fails: REFLECT",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7freflected|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "miss", missType = "REFLECT", spell = "Moonfire", spellId = 8921 } },
    { id = "spell at me fails: REFLECT",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:133:0:SPELL_MISSED|h|cffff1313Fireball|r|h |Haction:SPELL_MISSED|h|cff7f7f7freflected|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h. ",
      expect = { kind = "miss", missType = "REFLECT", spell = "Fireball", spellId = 133, toMe = true } },
    { id = "spell resisted, with an amount",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8921:0:SPELL_MISSED|h|cffffffffMoonfire|r|h |Haction:SPELL_MISSED|h|cff7f7f7fresisted|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (40 Resisted) ",
      expect = { fromMe = true, kind = "miss", missType = "RESIST", resisted = 40, spell = "Moonfire", spellId = 8921 } },
    { id = "spell with brackets in its name misses",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16857:0:SPELL_MISSED|h|cffffffffFaerie Fire (Feral)|r|h |Haction:SPELL_MISSED|h|cff7f7f7fMissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Missed) ",
      expect = { fromMe = true, kind = "miss", missType = "MISS", spell = "Faerie Fire (Feral)", spellId = 16857 } },
    { id = "spell with brackets in its name is resisted",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16857:0:SPELL_MISSED|h|cffffffffFaerie Fire (Feral)|r|h |Haction:SPELL_MISSED|h|cff7f7f7fresisted|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "miss", missType = "RESIST", spell = "Faerie Fire (Feral)", spellId = 16857 } },
    { id = "heal on myself",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:5185:0:SPELL_HEAL|h|cffffffffHealing Touch|r|h |Haction:SPELL_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff380|r |cffffffffNature|r. (120 Overhealed) ",
      expect = { amount = 380, fromMe = true, kind = "heal", overheal = 120, spell = "Healing Touch", spellId = 5185, toMe = true, unit = "Nature" } },
    { id = "heal on myself, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:5185:0:SPELL_HEAL|h|cffffffffHealing Touch|r|h |Haction:SPELL_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff1,500|r |cffffffffNature|r. (Critical) ",
      expect = { amount = 1500, crit = true, fromMe = true, kind = "heal", spell = "Healing Touch", spellId = 5185, toMe = true, unit = "Nature" } },
    { id = "heal on myself, all overheal",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:5185:0:SPELL_HEAL|h|cffffffffHealing Touch|r|h |Haction:SPELL_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff0|r |cffffffffNature|r. (500 Overhealed) ",
      expect = { amount = 0, fromMe = true, kind = "heal", overheal = 500, spell = "Healing Touch", spellId = 5185, toMe = true, unit = "Nature" } },
    { id = "heal on a friend",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:774:0:SPELL_HEAL|h|cffffffffRejuvenation|r|h |Haction:SPELL_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF2:Anduin Gabgubman|hAnduin Gabgubman|h |cffffffff61|r |cffffffffNature|r. ",
      expect = { amount = 61, fromMe = true, kind = "heal", spell = "Rejuvenation", spellId = 774, unit = "Nature" } },
    { id = "heal on a friend, overheal, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:2061:0:SPELL_HEAL|h|cffffffffFlash Heal|r|h |Haction:SPELL_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF2:Anduin Gabgubman|hAnduin Gabgubman|h |cffffffff1,034|r |cffffffffHoly|r. (200 Overhealed) (Critical) ",
      expect = { amount = 1034, crit = true, fromMe = true, kind = "heal", overheal = 200, spell = "Flash Heal", spellId = 2061, unit = "Holy" } },
    { id = "a friend's heal on me",
      raw = "|Hunit:Player-5555-0ABCDEF2:Anduin Gabgubman|hAnduin Gabgubman|h |Hspell:2061:0:SPELL_HEAL|h|cff82f4ffFlash Heal|r|h |Haction:SPELL_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cff82f4ff300|r |cff82f4ffHoly|r. ",
      expect = { amount = 300, kind = "heal", spell = "Flash Heal", spellId = 2061, toMe = true, unit = "Holy" } },
    { id = "heal tick on myself",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:774:0:SPELL_PERIODIC_HEAL|h|cffffffffRejuvenation|r|h |Haction:SPELL_PERIODIC_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff32|r |cffffffffNature|r. ",
      expect = { amount = 32, fromMe = true, kind = "heal", periodic = true, spell = "Rejuvenation", spellId = 774, toMe = true, unit = "Nature" } },
    { id = "heal tick on a friend, overheal, crit",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:774:0:SPELL_PERIODIC_HEAL|h|cffffffffRejuvenation|r|h |Haction:SPELL_PERIODIC_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF2:Anduin Gabgubman|hAnduin Gabgubman|h |cffffffff22|r |cffffffffNature|r. (10 Overhealed) (Critical) ",
      expect = { amount = 22, crit = true, fromMe = true, kind = "heal", overheal = 10, periodic = true, spell = "Rejuvenation", spellId = 774, unit = "Nature" } },
    { id = "a friend's heal tick on me",
      raw = "|Hunit:Player-5555-0ABCDEF2:Anduin Gabgubman|hAnduin Gabgubman|h |Hspell:139:0:SPELL_PERIODIC_HEAL|h|cff82f4ffRenew|r|h |Haction:SPELL_PERIODIC_HEAL|h|cff7f7f7fhealed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cff82f4ff45|r |cff82f4ffHoly|r. ",
      expect = { amount = 45, kind = "heal", periodic = true, spell = "Renew", spellId = 139, toMe = true, unit = "Holy" } },
    { id = "rage gained",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:2687:0:SPELL_ENERGIZE|h|cffffffffBloodrage|r|h |Haction:SPELL_ENERGIZE|h|cff7f7f7fenergized|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff10|r (Rage). ",
      expect = { amount = 10, fromMe = true, kind = "energize", spell = "Bloodrage", spellId = 2687, toMe = true, unit = "Rage" } },
    { id = "mana gained, thousands",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:12051:0:SPELL_ENERGIZE|h|cffffffffEvocation|r|h |Haction:SPELL_ENERGIZE|h|cff7f7f7fenergized|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff1,200|r (Mana). ",
      expect = { amount = 1200, fromMe = true, kind = "energize", spell = "Evocation", spellId = 12051, toMe = true, unit = "Mana" } },
    { id = "mana gained from a friend",
      raw = "|Hunit:Player-5555-0ABCDEF2:Anduin Gabgubman|hAnduin Gabgubman|h |Hspell:5677:0:SPELL_ENERGIZE|h|cff82f4ffMana Spring|r|h |Haction:SPELL_ENERGIZE|h|cff7f7f7fenergized|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cff82f4ff10|r (Mana). ",
      expect = { amount = 10, kind = "energize", spell = "Mana Spring", spellId = 5677, toMe = true, unit = "Mana" } },
    { id = "rage tick",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:2687:0:SPELL_PERIODIC_ENERGIZE|h|cffffffffBloodrage|r|h |Haction:SPELL_PERIODIC_ENERGIZE|h|cff7f7f7fenergized|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff1|r (Rage). ",
      expect = { amount = 1, fromMe = true, kind = "energize", periodic = true, spell = "Bloodrage", spellId = 2687, toMe = true, unit = "Rage" } },
    { id = "rage gained, some wasted",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:2687:0:SPELL_ENERGIZE|h|cffffffffBloodrage|r|h |Haction:SPELL_ENERGIZE|h|cff7f7f7fenergized|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff10|r (Rage). (4 Overenergized) ",
      expect = { amount = 10, fromMe = true, kind = "energize", spell = "Bloodrage", spellId = 2687, toMe = true, unit = "Rage" } },
    { id = "my kill",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |Haction:PARTY_KILL|h|cff7f7f7fkilled|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "kill" } },
    { id = "pet's kill",
      raw = "|Hunit:Pet-0-1-2-3-4-000002:Fluffy Zapsu|hFluffy Zapsu|h |Haction:PARTY_KILL|h|cff7f7f7fkilled|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { kind = "kill", srcGUID = "Pet-0-1-2-3-4-000002" } },
    { id = "a mob dies",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Haction:UNIT_DIED|h|cff7f7f7fdied|r|h. ",
      expect = { kind = "died" } },
    { id = "I die (a death recap link, not a sentence)",
      raw = "|Hdeath:7|h[You died.]|h",
      expect = { fromMe = true, kind = "died" } },
    { id = "a totem is destroyed",
      raw = "|Hunit:Creature-9:Searing Totem|hSearing Totem|h |Haction:UNIT_DESTROYED|h|cff7f7f7fdestroyed|r|h. ",
      expect = { kind = "died" } },
    { id = "interrupt",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:1766:0:SPELL_INTERRUPT|h|cffffffffKick|r|h |Haction:SPELL_INTERRUPT|h|cff7f7f7finterrupted|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = { fromMe = true, kind = "interrupt", spell = "Kick", spellId = 1766 } },
    { id = "interrupted",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:6552:0:SPELL_INTERRUPT|h|cffff1313Pummel|r|h |Haction:SPELL_INTERRUPT|h|cff7f7f7finterrupted|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYour|h. ",
      expect = { kind = "interrupt", spell = "Pummel", spellId = 6552, toMe = true } },
    { id = "dispel",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:370:0:SPELL_DISPEL|h|cffffffffPurge|r|h |Haction:SPELL_DISPEL|h|cff7f7f7fdispelled|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:1243:0:SPELL_DISPEL|h|cffffffffPower Word: Fortitude|r|h. ",
      expect = { fromMe = true, kind = "dispel", spell = "Purge", spellId = 370 } },
    { id = "cleanse a friend",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:4987:0:SPELL_DISPEL|h|cffffffffCleanse|r|h |Haction:SPELL_DISPEL|h|cff7f7f7fcleansed|r|h |Hunit:Player-5555-0ABCDEF2:Anduin Gabgubman|hAnduin Gabgubman|h |Hspell:172:0:SPELL_DISPEL|h|cffffffffCorruption|r|h. ",
      expect = { fromMe = true, kind = "dispel", spell = "Cleanse", spellId = 4987 } },
    { id = "cleanse myself",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:4987:0:SPELL_DISPEL|h|cffffffffCleanse|r|h |Haction:SPELL_DISPEL|h|cff7f7f7fcleansed|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:172:0:SPELL_DISPEL|h|cffffffffCorruption|r|h. ",
      expect = { fromMe = true, kind = "dispel", spell = "Cleanse", spellId = 4987, toMe = true } },
    { id = "my buff is dispelled",
      raw = "|Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:370:0:SPELL_DISPEL|h|cffff1313Purge|r|h |Haction:SPELL_DISPEL|h|cff7f7f7fdispelled|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:1243:0:SPELL_DISPEL|h|cffff1313Power Word: Fortitude|r|h. ",
      expect = { kind = "dispel", spell = "Purge", spellId = 370, toMe = true } },
    { id = "spell steal",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:30449:0:SPELL_STOLEN|h|cffffffffSpellsteal|r|h |Haction:SPELL_STOLEN|h|cff7f7f7fstole|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |Hspell:1243:0:SPELL_STOLEN|h|cffffffffPower Word: Fortitude|r|h. ",
      expect = { fromMe = true, kind = "dispel", spell = "Spellsteal", spellId = 30449 } },
    { id = "a spell's kill (\"You killed\" follows it)",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:1:0:SPELL_INSTAKILL|h|cffffffffExecute Order|r|h |Haction:SPELL_INSTAKILL|h|cff7f7f7fkilled|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = nil },
    { id = "leech",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:5138:0:SPELL_LEECH|h|cffffffffDrain Mana|r|h |Haction:SPELL_LEECH|h|cff7f7f7fdrained|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff40|r (Mana). 40 Mana Gained ",
      expect = nil },
    { id = "drain",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:5138:0:SPELL_DRAIN|h|cffffffffDrain Mana|r|h |Haction:SPELL_DRAIN|h|cff7f7f7fdrained|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff40|r (Mana). ",
      expect = nil },
    { id = "leech tick",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:5138:0:SPELL_PERIODIC_LEECH|h|cffffffffDrain Mana|r|h |Haction:SPELL_PERIODIC_LEECH|h|cff7f7f7fdrained|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff40|r (Mana). (40 Mana Gained) ",
      expect = nil },
    { id = "extra attacks",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:8516:0:SPELL_EXTRA_ATTACKS|h|cffffffffWindfury Attack|r|h |Haction:SPELL_EXTRA_ATTACKS|h|cff7f7f7fgranted extra attacks|r|h |Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |cffffffff2|r. ",
      expect = nil },
    { id = "summon",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:3599:0:SPELL_SUMMON|h|cffffffffSearing Totem|r|h |Haction:SPELL_SUMMON|h|cff7f7f7fsummoned|r|h |Hunit:Creature-9:Searing Totem|hSearing Totem|h. ",
      expect = nil },
    { id = "cast",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|hYou|h |Haction:SPELL_CAST_SUCCESS|h|cff7f7f7fcast|r|h |Hspell:133:0:SPELL_CAST_SUCCESS|h|cffffffffFireball|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. ",
      expect = nil },
    { id = "look: timestamps",
      raw = "06:13:20> |Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffffffClaw|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h |cffffffff50|r |cffffffffPhysical|r. (1 Blocked) (Critical) ",
      expect = { amount = 50, blocked = 1, crit = true, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "look: timestamps, a miss",
      raw = "06:13:20> |Hunit:Player-5555-0ABCDEF1:Abla|hYour|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|hBristleback Hunter Fizzlesticks|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "DODGE" } },
    { id = "look: braces around names",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|h|cFFFFFFFF[|rYour|cFFFFFFFF]|r|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffffffClaw|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|h|cFFFFFFFF[|rBristleback Hunter Fizzlesticks|cFFFFFFFF]|r|h |cffffffff50|r |cffffffffPhysical|r. (1 Blocked) (Critical) ",
      expect = { amount = 50, blocked = 1, crit = true, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "look: braces around names, a miss",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|h|cFFFFFFFF[|rYour|cFFFFFFFF]|r|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|h|cFFFFFFFF[|rBristleback Hunter Fizzlesticks|cFFFFFFFF]|r|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "DODGE" } },
    { id = "look: braces around names and spells",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|h|cFFFFFFFF[|rYour|cFFFFFFFF]|r|h |Hspell:16827:0:SPELL_DAMAGE|h|cFFFFFFFF[|r|cffffffffClaw|r|cFFFFFFFF]|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|h|cFFFFFFFF[|rBristleback Hunter Fizzlesticks|cFFFFFFFF]|r|h |cffffffff50|r |cffffffffPhysical|r. (1 Blocked) (Critical) ",
      expect = { amount = 50, blocked = 1, crit = true, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "look: braces around names and spells, a miss",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|h|cFFFFFFFF[|rYour|cFFFFFFFF]|r|h |Haction:SWING_MISSED|h|cFFFFFFFF[|r|cffffffffMelee|r|cFFFFFFFF]|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|h|cFFFFFFFF[|rBristleback Hunter Fizzlesticks|cFFFFFFFF]|r|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "DODGE" } },
    { id = "look: names coloured",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|h|cffb2b2b2Your|r|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffffffClaw|r|h |Haction:SPELL_DAMAGE|hhit|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|h|cffbf0c0cBristleback Hunter Fizzlesticks|r|h |cffffffff50|r |cffffffffPhysical|r. (1 Blocked) (Critical) ",
      expect = { amount = 50, blocked = 1, crit = true, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "look: names coloured, a miss",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|h|cffb2b2b2Your|r|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|h|cffbf0c0cBristleback Hunter Fizzlesticks|r|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "DODGE" } },
    { id = "look: everything coloured",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|h|cffb2b2b2Your|r|h |Hspell:16827:0:SPELL_DAMAGE|h|cffffff00Claw|r|h |Haction:SPELL_DAMAGE|h|cff7f7f7fhit|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|h|cffbf0c0cBristleback Hunter Fizzlesticks|r|h |cffffff0050|r |cffffff00Physical|r. (1 Blocked) (Critical) ",
      expect = { amount = 50, blocked = 1, crit = true, fromMe = true, kind = "damage", spell = "Claw", spellId = 16827, unit = "Physical" } },
    { id = "look: everything coloured, a miss",
      raw = "|Hunit:Player-5555-0ABCDEF1:Abla|h|cffb2b2b2Your|r|h |Haction:SWING_MISSED|h|cffffffffMelee|r|h |Haction:SWING_MISSED|h|cff7f7f7fmissed|r|h |Hunit:Creature-0-1-2-3-4-000001:Bristleback Hunter Fizzlesticks|h|cffbf0c0cBristleback Hunter Fizzlesticks|r|h. (Dodged) ",
      expect = { fromMe = true, kind = "miss", melee = true, missType = "DODGE" } },
}
